// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { safeLocalStorage } from '@/lib/ssrGuard';
import type { Database } from './types';

const SUPABASE_URL = "https://zkgkepieivzprpvbbtyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprZ2tlcGllaXZ6cHJwdmJidHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzg4NzYsImV4cCI6MjA2Njk1NDg3Nn0.QzlFWGBQqTtOCbsL6LV6jjM3fl4WZkMx_nQDIE65XxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeLocalStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});